### ISSUE TITLE
Dates variables "%{+YYYY.MM.dd}" do not exist

### ISSUE THREAD

**Issue by AlexAkulov** [veino/bitfan#16]
Hello! 
Usually in Logstash I used this included variables "%{+YYYY.MM.dd}" for writing data by days. But now I suspect that it doesn't work in bitfan. It would be great to add them.

My config is:
```
input  { stdin{} }
filter {
    mutate {
      add_field => {"date"=>"%{+YYYY.MM.dd}"}
    }
}
output { stdout { codec => rubydebug {}}}
```
Logstash output is:
```
{
       "message" => "qwe",
      "@version" => "1",
    "@timestamp" => "2017-02-07T19:32:13.558Z",
          "host" => "testelastic",
          "date" => "2017.02.07"
}
```
bitfan output is:
```
&{
  "@timestamp": "2017-02-08T00:36:27.113+05:00",
  "date":       "%{+YYYY.MM.dd}",
  "host":       "idea-PC",
  "message":    "qwe",
  "tags":       []interface {}{},
}
```

**Comment by vjeantet** [comment]
Hello, yes bitfan yet does not support sprintf format
https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#sprintf

I will implement this

**Comment by vjeantet** [comment]
golang time format is a ..... :(

golang : https://golang.org/src/time/format.go
joda : http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html

Do you know any package which can format a time from a common format like `YYYY.MM.dd` ?

**Comment by AlexAkulov** [comment]
joda format is not necessary for me, I would be satisfied if I could use something like this `"%{stdLongYear}.%{stdZeroMonth}.%{stdZeroDay}"`

**Comment by vjeantet** [comment]
package jodaTime for go ! https://github.com/vjeantet/jodaTime
